trigger:
  branches:
    include:
      - master
      - feature/*
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.7.12
      endpoint: github

variables:
  - group: rsg-bot
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"

jobs:
  - job: GitVersion
    pool:
      vmImage: "VS2017-Win2016"
    steps:
      - template: gitversion/store.yml@rsg
        parameters:
          NuGetVersion: "5.2.0"

  - template: pipeline/nuke-job.yml@rsg
    parameters:
      name: 'Windows'
      dependsOn: GitVersion
      vmImage: "windows-2019"
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      GitHub: true
      GitHubPackages: false
      DotNetVersion: "2.2.300"
      DotNet3Version: "3.0.100-preview6-012264"
      NuGetVersion: "4.7.1"
      
  - job: Publish
    pool:
      vmImage: "windows-2019"
    dependsOn:
      - Windows
    steps:
      - download: current
        artifact: 'Nupkg - Windows'
      - template: standard/nuget-push.yml@rsg
        parameters:
          Artifacts: "$(Pipeline.Workspace)/Nupkg - Windows/"
          NuGetVersion: "5.2.0"
          Verbosity: $(Verbosity)
          GitHubPackages: false